# Generated by Django 2.0.3 on 2018-03-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MachineNo', models.CharField(max_length=10, unique=True)),
                ('GrainType', models.CharField(max_length=10)),
                ('Enable', models.IntegerField()),
                ('GrainMoisture', models.FloatField(blank=True)),
                ('Loss', models.FloatField(blank=True)),
            ],
        ),
    ]
