# Generated by Django 2.0.3 on 2018-03-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Loss',
            field=models.FloatField(),
        ),
    ]
