# Generated by Django 2.0.3 on 2018-03-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180331_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Loss',
            field=models.FloatField(blank=True),
        ),
    ]
