# Generated by Django 2.0.3 on 2018-03-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_machines_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Enable',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='machines',
            name='GrainType',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
