# Generated by Django 2.0.3 on 2018-03-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20180331_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='Enable',
            field=models.IntegerField(null=True),
        ),
    ]
