# Generated by Django 2.0.3 on 2018-03-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20180331_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='ValueCut',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
