# Generated by Django 2.0.3 on 2018-03-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20180331_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines',
            old_name='MachineNo',
            new_name='StackNo',
        ),
    ]
