# Generated by Django 2.0.3 on 2018-03-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20180331_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machines',
            name='GrainType',
        ),
        migrations.AddField(
            model_name='machines',
            name='TokenNo',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machines',
            name='StackNo',
            field=models.CharField(max_length=10),
        ),
    ]
