# Generated by Django 2.0.3 on 2018-03-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20180331_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines',
            old_name='GrainTypTOkene',
            new_name='GrainType',
        ),
    ]
