# Generated by Django 2.0.3 on 2018-03-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20180331_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines',
            old_name='StackNo',
            new_name='TokenNo',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='GrainType',
        ),
        migrations.AddField(
            model_name='machines',
            name='StackNO',
            field=models.CharField(default=436, max_length=10),
            preserve_default=False,
        ),
    ]
