# Generated by Django 2.0.3 on 2018-03-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20180331_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines',
            old_name='StackNO',
            new_name='StackNo',
        ),
    ]
